<?php

namespace App\Support;

/**
 * Gecureerde set merk-iconen (SVG, CC0-licentie via simple-icons.org) die
 * lokaal meegeleverd wordt in assets/icons/brands/ — geen enkele runtime-
 * aanroep naar een externe dienst, past bij de rest van de app (alles
 * lokaal, ook offline bruikbaar). Gebruikt door de icoon-koppelpagina om
 * een omschrijving (bijv. "Netflix") aan een icoon te koppelen.
 */
final class BrandIcons
{
    /** @var array<string, array{title: string, hex: string}> */
    private const ICONS = [
        '1password' => ['title' => '1Password', 'hex' => '145FE4'],
        'adidas' => ['title' => 'Adidas', 'hex' => '000000'],
        'adyen' => ['title' => 'Adyen', 'hex' => '0ABF53'],
        'airbnb' => ['title' => 'Airbnb', 'hex' => 'FF5A5F'],
        'albertheijn' => ['title' => 'Albert Heijn', 'hex' => '04ACE6'],
        'aliexpress' => ['title' => 'AliExpress', 'hex' => 'FF4747'],
        'americanexpress' => ['title' => 'American Express', 'hex' => '2E77BC'],
        'android' => ['title' => 'Android', 'hex' => '3DDC84'],
        'apple' => ['title' => 'Apple', 'hex' => '000000'],
        'applemusic' => ['title' => 'Apple Music', 'hex' => 'FA243C'],
        'appletv' => ['title' => 'Apple TV', 'hex' => '000000'],
        'asana' => ['title' => 'Asana', 'hex' => 'F06A6A'],
        'audible' => ['title' => 'Audible', 'hex' => 'F8991C'],
        'avast' => ['title' => 'Avast', 'hex' => 'FF7800'],
        'bandcamp' => ['title' => 'Bandcamp', 'hex' => '408294'],
        'bitdefender' => ['title' => 'Bitdefender', 'hex' => 'ED1C24'],
        'bookingdotcom' => ['title' => 'Booking.com', 'hex' => '003A9A'],
        'bt' => ['title' => 'BT', 'hex' => '6400AA'],
        'bunq' => ['title' => 'bunq', 'hex' => '3394D7'],
        'burgerking' => ['title' => 'Burger King', 'hex' => 'D62300'],
        'cloudflare' => ['title' => 'Cloudflare', 'hex' => 'F38020'],
        'coursera' => ['title' => 'Coursera', 'hex' => '0056D2'],
        'crunchyroll' => ['title' => 'Crunchyroll', 'hex' => 'FF5E00'],
        'dailymotion' => ['title' => 'Dailymotion', 'hex' => '0A0A0A'],
        'deezer' => ['title' => 'Deezer', 'hex' => 'A238FF'],
        'deliveroo' => ['title' => 'Deliveroo', 'hex' => '00CCBC'],
        'digitalocean' => ['title' => 'DigitalOcean', 'hex' => '0080FF'],
        'discord' => ['title' => 'Discord', 'hex' => '5865F2'],
        'dropbox' => ['title' => 'Dropbox', 'hex' => '0061FF'],
        'duolingo' => ['title' => 'Duolingo', 'hex' => '58CC02'],
        'ea' => ['title' => 'EA', 'hex' => '000000'],
        'ebay' => ['title' => 'eBay', 'hex' => 'E53238'],
        'emby' => ['title' => 'Emby', 'hex' => '52B54B'],
        'etsy' => ['title' => 'Etsy', 'hex' => 'F16521'],
        'evernote' => ['title' => 'Evernote', 'hex' => '00A82D'],
        'expressvpn' => ['title' => 'ExpressVPN', 'hex' => 'DA3940'],
        'facebook' => ['title' => 'Facebook', 'hex' => '0866FF'],
        'figma' => ['title' => 'Figma', 'hex' => 'F24E1E'],
        'fitbit' => ['title' => 'Fitbit', 'hex' => '00B0B9'],
        'fortnite' => ['title' => 'Fortnite', 'hex' => '000000'],
        'garmin' => ['title' => 'Garmin', 'hex' => '000000'],
        'github' => ['title' => 'GitHub', 'hex' => '181717'],
        'gmail' => ['title' => 'Gmail', 'hex' => 'EA4335'],
        'godaddy' => ['title' => 'GoDaddy', 'hex' => '1BDBDB'],
        'google' => ['title' => 'Google', 'hex' => '4285F4'],
        'googlecalendar' => ['title' => 'Google Calendar', 'hex' => '4285F4'],
        'googledrive' => ['title' => 'Google Drive', 'hex' => '4285F4'],
        'googlephotos' => ['title' => 'Google Photos', 'hex' => '4285F4'],
        'googleplay' => ['title' => 'Google Play', 'hex' => '414141'],
        'handm' => ['title' => 'H&M', 'hex' => 'E50010'],
        'hbomax' => ['title' => 'HBO Max', 'hex' => '000000'],
        'headspace' => ['title' => 'Headspace', 'hex' => 'F47D31'],
        'hellofresh' => ['title' => 'HelloFresh', 'hex' => '99CC33'],
        'hostinger' => ['title' => 'Hostinger', 'hex' => '673DE6'],
        'icloud' => ['title' => 'iCloud', 'hex' => '3693F3'],
        'ikea' => ['title' => 'IKEA', 'hex' => '0058A3'],
        'instagram' => ['title' => 'Instagram', 'hex' => 'FF0069'],
        'ionos' => ['title' => 'Ionos', 'hex' => '003D8F'],
        'jellyfin' => ['title' => 'Jellyfin', 'hex' => '00A4DC'],
        'justeat' => ['title' => 'Just Eat', 'hex' => 'FF8000'],
        'kaspersky' => ['title' => 'Kaspersky', 'hex' => '006D5C'],
        'kfc' => ['title' => 'KFC', 'hex' => 'F40027'],
        'klarna' => ['title' => 'Klarna', 'hex' => 'FFB3C7'],
        'klm' => ['title' => 'KLM', 'hex' => '00A1DE'],
        'lastpass' => ['title' => 'LastPass', 'hex' => 'D32D27'],
        'lidl' => ['title' => 'Lidl', 'hex' => '0050AA'],
        'malwarebytes' => ['title' => 'Malwarebytes', 'hex' => '0D3ECC'],
        'mastercard' => ['title' => 'MasterCard', 'hex' => 'EB001B'],
        'max' => ['title' => 'Max', 'hex' => '525252'],
        'mcafee' => ['title' => 'McAfee', 'hex' => 'C01818'],
        'mcdonalds' => ['title' => 'McDonald\'s', 'hex' => 'FBC817'],
        'mediamarkt' => ['title' => 'MediaMarkt', 'hex' => 'DF0000'],
        'mixcloud' => ['title' => 'Mixcloud', 'hex' => '5000FF'],
        'monzo' => ['title' => 'Monzo', 'hex' => '14233C'],
        'n26' => ['title' => 'N26', 'hex' => '48AC98'],
        'namecheap' => ['title' => 'Namecheap', 'hex' => 'DE3723'],
        'netflix' => ['title' => 'Netflix', 'hex' => 'E50914'],
        'netgear' => ['title' => 'NETGEAR', 'hex' => '2C262D'],
        'nike' => ['title' => 'Nike', 'hex' => '111111'],
        'nordvpn' => ['title' => 'NordVPN', 'hex' => '4687FF'],
        'norton' => ['title' => 'Norton', 'hex' => 'FFE01A'],
        'notion' => ['title' => 'Notion', 'hex' => '000000'],
        'o2' => ['title' => 'O2', 'hex' => '0050FF'],
        'odido' => ['title' => 'Odido', 'hex' => '2C72FF'],
        'onlyfans' => ['title' => 'OnlyFans', 'hex' => '00AFF0'],
        'origin' => ['title' => 'Origin', 'hex' => 'F56C2D'],
        'otto' => ['title' => 'Otto', 'hex' => 'D4021D'],
        'paramountplus' => ['title' => 'Paramount+', 'hex' => '0064FF'],
        'patreon' => ['title' => 'Patreon', 'hex' => '000000'],
        'paypal' => ['title' => 'PayPal', 'hex' => '002991'],
        'peloton' => ['title' => 'Peloton', 'hex' => '181A1D'],
        'philipshue' => ['title' => 'Philips Hue', 'hex' => '0065D3'],
        'picnic' => ['title' => 'Picnic', 'hex' => 'E1171E'],
        'pinterest' => ['title' => 'Pinterest', 'hex' => 'BD081C'],
        'playstation' => ['title' => 'PlayStation', 'hex' => '0070D1'],
        'plex' => ['title' => 'Plex', 'hex' => 'EBAF00'],
        'reddit' => ['title' => 'Reddit', 'hex' => 'FF4500'],
        'revolut' => ['title' => 'Revolut', 'hex' => '191C1F'],
        'ring' => ['title' => 'Ring', 'hex' => '1C9AD6'],
        'roblox' => ['title' => 'Roblox', 'hex' => '000000'],
        'ryanair' => ['title' => 'Ryanair', 'hex' => '073590'],
        'samsung' => ['title' => 'Samsung', 'hex' => '1428A0'],
        'shell' => ['title' => 'Shell', 'hex' => 'FFD500'],
        'signal' => ['title' => 'Signal', 'hex' => '3B45FD'],
        'skillshare' => ['title' => 'Skillshare', 'hex' => '00FF84'],
        'sky' => ['title' => 'Sky', 'hex' => '0072C9'],
        'snapchat' => ['title' => 'Snapchat', 'hex' => 'FFFC00'],
        'sony' => ['title' => 'Sony', 'hex' => 'FFFFFF'],
        'soundcloud' => ['title' => 'SoundCloud', 'hex' => 'FF5500'],
        'spotify' => ['title' => 'Spotify', 'hex' => '1ED760'],
        'squarespace' => ['title' => 'Squarespace', 'hex' => '000000'],
        'starbucks' => ['title' => 'Starbucks', 'hex' => '006241'],
        'starlingbank' => ['title' => 'Starling Bank', 'hex' => '6935D3'],
        'steam' => ['title' => 'Steam', 'hex' => '000000'],
        'strava' => ['title' => 'Strava', 'hex' => 'FC4C02'],
        'telegram' => ['title' => 'Telegram', 'hex' => '26A5E4'],
        'tesla' => ['title' => 'Tesla', 'hex' => 'CC0000'],
        'tidal' => ['title' => 'TIDAL', 'hex' => '000000'],
        'tiktok' => ['title' => 'TikTok', 'hex' => '000000'],
        'tinder' => ['title' => 'Tinder', 'hex' => 'FF6B6B'],
        'todoist' => ['title' => 'Todoist', 'hex' => 'E44332'],
        'tplink' => ['title' => 'TP-Link', 'hex' => '4ACBD6'],
        'trello' => ['title' => 'Trello', 'hex' => '0052CC'],
        'twitch' => ['title' => 'Twitch', 'hex' => '9146FF'],
        'uber' => ['title' => 'Uber', 'hex' => '000000'],
        'ubereats' => ['title' => 'Uber Eats', 'hex' => '06C167'],
        'ubiquiti' => ['title' => 'Ubiquiti', 'hex' => '0559C9'],
        'ubisoft' => ['title' => 'Ubisoft', 'hex' => '000000'],
        'udemy' => ['title' => 'Udemy', 'hex' => 'A435F0'],
        'uniqlo_ja' => ['title' => 'Uniqlo', 'hex' => 'FF0000'],
        'vercel' => ['title' => 'Vercel', 'hex' => '000000'],
        'vimeo' => ['title' => 'Vimeo', 'hex' => '1AB7EA'],
        'vinted' => ['title' => 'Vinted', 'hex' => '007782'],
        'virgin' => ['title' => 'Virgin', 'hex' => 'E10A0A'],
        'virginmedia' => ['title' => 'Virgin Media', 'hex' => 'ED1A37'],
        'visa' => ['title' => 'Visa', 'hex' => '1A1F71'],
        'vodafone' => ['title' => 'Vodafone', 'hex' => 'E60000'],
        'whatsapp' => ['title' => 'WhatsApp', 'hex' => '25D366'],
        'wise' => ['title' => 'Wise', 'hex' => '9FE870'],
        'wix' => ['title' => 'Wix', 'hex' => '0C6EFC'],
        'wordpress' => ['title' => 'WordPress', 'hex' => '21759B'],
        'x' => ['title' => 'X', 'hex' => '000000'],
        'youtube' => ['title' => 'YouTube', 'hex' => 'FF0000'],
        'youtubemusic' => ['title' => 'YouTube Music', 'hex' => 'FF0000'],
        'youtubetv' => ['title' => 'YouTube TV', 'hex' => 'FF0000'],
        'zalando' => ['title' => 'Zalando', 'hex' => 'FF6900'],
        'ziggo' => ['title' => 'Ziggo', 'hex' => 'F48C00'],
        'zoom' => ['title' => 'Zoom', 'hex' => '0B5CFF'],
    ];

    /** @return array<string, array{title: string, hex: string}> */
    public static function all(): array
    {
        return self::ICONS;
    }

    public static function exists(string $slug): bool
    {
        return isset(self::ICONS[$slug]);
    }

    public static function title(string $slug): ?string
    {
        return self::ICONS[$slug]['title'] ?? null;
    }
}
